package com.hngg.jianshi.data.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hngg.jianshi.data.database.bean.CollectionInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLLECTION_INFO".
*/
public class CollectionInfoDao extends AbstractDao<CollectionInfo, Long> {

    public static final String TABLENAME = "COLLECTION_INFO";

    /**
     * Properties of entity CollectionInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VideoId = new Property(1, Long.class, "videoId", false, "VIDEO_ID");
        public final static Property VideoName = new Property(2, String.class, "videoName", false, "VIDEO_NAME");
        public final static Property Poster = new Property(3, String.class, "poster", false, "POSTER");
        public final static Property PlayUrl = new Property(4, String.class, "playUrl", false, "PLAY_URL");
        public final static Property VideoDesc = new Property(5, String.class, "videoDesc", false, "VIDEO_DESC");
        public final static Property Category = new Property(6, String.class, "category", false, "CATEGORY");
        public final static Property Duration = new Property(7, int.class, "duration", false, "DURATION");
        public final static Property VideoSize = new Property(8, Long.class, "videoSize", false, "VIDEO_SIZE");
        public final static Property AuthorId = new Property(9, Long.class, "authorId", false, "AUTHOR_ID");
        public final static Property AuthorName = new Property(10, String.class, "authorName", false, "AUTHOR_NAME");
        public final static Property AuthorIcon = new Property(11, String.class, "authorIcon", false, "AUTHOR_ICON");
        public final static Property AuthorDesc = new Property(12, String.class, "authorDesc", false, "AUTHOR_DESC");
    }


    public CollectionInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CollectionInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLLECTION_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VIDEO_ID\" INTEGER," + // 1: videoId
                "\"VIDEO_NAME\" TEXT," + // 2: videoName
                "\"POSTER\" TEXT," + // 3: poster
                "\"PLAY_URL\" TEXT," + // 4: playUrl
                "\"VIDEO_DESC\" TEXT," + // 5: videoDesc
                "\"CATEGORY\" TEXT," + // 6: category
                "\"DURATION\" INTEGER NOT NULL ," + // 7: duration
                "\"VIDEO_SIZE\" INTEGER," + // 8: videoSize
                "\"AUTHOR_ID\" INTEGER," + // 9: authorId
                "\"AUTHOR_NAME\" TEXT," + // 10: authorName
                "\"AUTHOR_ICON\" TEXT," + // 11: authorIcon
                "\"AUTHOR_DESC\" TEXT);"); // 12: authorDesc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLLECTION_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CollectionInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindLong(2, videoId);
        }
 
        String videoName = entity.getVideoName();
        if (videoName != null) {
            stmt.bindString(3, videoName);
        }
 
        String poster = entity.getPoster();
        if (poster != null) {
            stmt.bindString(4, poster);
        }
 
        String playUrl = entity.getPlayUrl();
        if (playUrl != null) {
            stmt.bindString(5, playUrl);
        }
 
        String videoDesc = entity.getVideoDesc();
        if (videoDesc != null) {
            stmt.bindString(6, videoDesc);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(7, category);
        }
        stmt.bindLong(8, entity.getDuration());
 
        Long videoSize = entity.getVideoSize();
        if (videoSize != null) {
            stmt.bindLong(9, videoSize);
        }
 
        Long authorId = entity.getAuthorId();
        if (authorId != null) {
            stmt.bindLong(10, authorId);
        }
 
        String authorName = entity.getAuthorName();
        if (authorName != null) {
            stmt.bindString(11, authorName);
        }
 
        String authorIcon = entity.getAuthorIcon();
        if (authorIcon != null) {
            stmt.bindString(12, authorIcon);
        }
 
        String authorDesc = entity.getAuthorDesc();
        if (authorDesc != null) {
            stmt.bindString(13, authorDesc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CollectionInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long videoId = entity.getVideoId();
        if (videoId != null) {
            stmt.bindLong(2, videoId);
        }
 
        String videoName = entity.getVideoName();
        if (videoName != null) {
            stmt.bindString(3, videoName);
        }
 
        String poster = entity.getPoster();
        if (poster != null) {
            stmt.bindString(4, poster);
        }
 
        String playUrl = entity.getPlayUrl();
        if (playUrl != null) {
            stmt.bindString(5, playUrl);
        }
 
        String videoDesc = entity.getVideoDesc();
        if (videoDesc != null) {
            stmt.bindString(6, videoDesc);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(7, category);
        }
        stmt.bindLong(8, entity.getDuration());
 
        Long videoSize = entity.getVideoSize();
        if (videoSize != null) {
            stmt.bindLong(9, videoSize);
        }
 
        Long authorId = entity.getAuthorId();
        if (authorId != null) {
            stmt.bindLong(10, authorId);
        }
 
        String authorName = entity.getAuthorName();
        if (authorName != null) {
            stmt.bindString(11, authorName);
        }
 
        String authorIcon = entity.getAuthorIcon();
        if (authorIcon != null) {
            stmt.bindString(12, authorIcon);
        }
 
        String authorDesc = entity.getAuthorDesc();
        if (authorDesc != null) {
            stmt.bindString(13, authorDesc);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CollectionInfo readEntity(Cursor cursor, int offset) {
        CollectionInfo entity = new CollectionInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // videoId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // videoName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // poster
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // playUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // videoDesc
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // category
            cursor.getInt(offset + 7), // duration
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // videoSize
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // authorId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // authorName
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // authorIcon
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // authorDesc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CollectionInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVideoId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setVideoName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPoster(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPlayUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVideoDesc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCategory(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDuration(cursor.getInt(offset + 7));
        entity.setVideoSize(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setAuthorId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setAuthorName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAuthorIcon(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAuthorDesc(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CollectionInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CollectionInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CollectionInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
