package com.hngg.jianshi.data.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hngg.jianshi.data.database.bean.CollectionInfo;
import com.hngg.jianshi.data.database.bean.PlayInfo;
import com.hngg.jianshi.data.database.bean.SearchInfo;
import com.hngg.jianshi.data.database.bean.VideoInfo;
import com.hngg.jianshi.data.database.bean.VideoResolutionInfo;
import com.hngg.jianshi.data.database.bean.VideoTaskInfo;

import com.hngg.jianshi.data.database.dao.CollectionInfoDao;
import com.hngg.jianshi.data.database.dao.PlayInfoDao;
import com.hngg.jianshi.data.database.dao.SearchInfoDao;
import com.hngg.jianshi.data.database.dao.VideoInfoDao;
import com.hngg.jianshi.data.database.dao.VideoResolutionInfoDao;
import com.hngg.jianshi.data.database.dao.VideoTaskInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionInfoDaoConfig;
    private final DaoConfig playInfoDaoConfig;
    private final DaoConfig searchInfoDaoConfig;
    private final DaoConfig videoInfoDaoConfig;
    private final DaoConfig videoResolutionInfoDaoConfig;
    private final DaoConfig videoTaskInfoDaoConfig;

    private final CollectionInfoDao collectionInfoDao;
    private final PlayInfoDao playInfoDao;
    private final SearchInfoDao searchInfoDao;
    private final VideoInfoDao videoInfoDao;
    private final VideoResolutionInfoDao videoResolutionInfoDao;
    private final VideoTaskInfoDao videoTaskInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionInfoDaoConfig = daoConfigMap.get(CollectionInfoDao.class).clone();
        collectionInfoDaoConfig.initIdentityScope(type);

        playInfoDaoConfig = daoConfigMap.get(PlayInfoDao.class).clone();
        playInfoDaoConfig.initIdentityScope(type);

        searchInfoDaoConfig = daoConfigMap.get(SearchInfoDao.class).clone();
        searchInfoDaoConfig.initIdentityScope(type);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        videoResolutionInfoDaoConfig = daoConfigMap.get(VideoResolutionInfoDao.class).clone();
        videoResolutionInfoDaoConfig.initIdentityScope(type);

        videoTaskInfoDaoConfig = daoConfigMap.get(VideoTaskInfoDao.class).clone();
        videoTaskInfoDaoConfig.initIdentityScope(type);

        collectionInfoDao = new CollectionInfoDao(collectionInfoDaoConfig, this);
        playInfoDao = new PlayInfoDao(playInfoDaoConfig, this);
        searchInfoDao = new SearchInfoDao(searchInfoDaoConfig, this);
        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);
        videoResolutionInfoDao = new VideoResolutionInfoDao(videoResolutionInfoDaoConfig, this);
        videoTaskInfoDao = new VideoTaskInfoDao(videoTaskInfoDaoConfig, this);

        registerDao(CollectionInfo.class, collectionInfoDao);
        registerDao(PlayInfo.class, playInfoDao);
        registerDao(SearchInfo.class, searchInfoDao);
        registerDao(VideoInfo.class, videoInfoDao);
        registerDao(VideoResolutionInfo.class, videoResolutionInfoDao);
        registerDao(VideoTaskInfo.class, videoTaskInfoDao);
    }
    
    public void clear() {
        collectionInfoDaoConfig.clearIdentityScope();
        playInfoDaoConfig.clearIdentityScope();
        searchInfoDaoConfig.clearIdentityScope();
        videoInfoDaoConfig.clearIdentityScope();
        videoResolutionInfoDaoConfig.clearIdentityScope();
        videoTaskInfoDaoConfig.clearIdentityScope();
    }

    public CollectionInfoDao getCollectionInfoDao() {
        return collectionInfoDao;
    }

    public PlayInfoDao getPlayInfoDao() {
        return playInfoDao;
    }

    public SearchInfoDao getSearchInfoDao() {
        return searchInfoDao;
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

    public VideoResolutionInfoDao getVideoResolutionInfoDao() {
        return videoResolutionInfoDao;
    }

    public VideoTaskInfoDao getVideoTaskInfoDao() {
        return videoTaskInfoDao;
    }

}
