package com.hngg.jianshi.data.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hngg.jianshi.data.database.bean.SearchInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_INFO".
*/
public class SearchInfoDao extends AbstractDao<SearchInfo, Long> {

    public static final String TABLENAME = "SEARCH_INFO";

    /**
     * Properties of entity SearchInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SearchField = new Property(1, String.class, "searchField", false, "SEARCH_FIELD");
        public final static Property SearchTime = new Property(2, Long.class, "searchTime", false, "SEARCH_TIME");
    }


    public SearchInfoDao(DaoConfig config) {
        super(config);
    }
    
    public SearchInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SEARCH_FIELD\" TEXT," + // 1: searchField
                "\"SEARCH_TIME\" INTEGER);"); // 2: searchTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String searchField = entity.getSearchField();
        if (searchField != null) {
            stmt.bindString(2, searchField);
        }
 
        Long searchTime = entity.getSearchTime();
        if (searchTime != null) {
            stmt.bindLong(3, searchTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String searchField = entity.getSearchField();
        if (searchField != null) {
            stmt.bindString(2, searchField);
        }
 
        Long searchTime = entity.getSearchTime();
        if (searchTime != null) {
            stmt.bindLong(3, searchTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SearchInfo readEntity(Cursor cursor, int offset) {
        SearchInfo entity = new SearchInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // searchField
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // searchTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSearchField(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSearchTime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SearchInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SearchInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
